name: Windows make

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: turtlebrowser/get-conan@main
      name: Install Conan
      id: conan
    - uses: actions/checkout@v2
    - name: Conan install
      run: conan install
    - name: cmake
      run: cmake .
    - name: make
      run: make
